services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5353:53/tcp"
      - "353:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Africa/Lagos # Set your timezone
      - WEBPASSWORD=your_secure_password # Set a secure admin password
      - PIHOLE_DNS_=8.8.8.8;8.8.4.4 # Upstream DNS servers (Google DNS in this example)
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge