version: '3'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./cloudbeaver-data:/opt/cloudbeaver/workspace
    environment:
      - CB_ADMIN_NAME=admin
      - CB_ADMIN_PASSWORD=your_secure_password
    restart: unless-stopped