services:
  postgres:
    image: postgres:12
    container_name: taskcafe-postgres
    environment:
      - POSTGRES_USER=taskcafe
      - POSTGRES_PASSWORD=taskcafe_secret
      - POSTGRES_DB=taskcafe
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  taskcafe:
    image: taskcafe/taskcafe:latest
    container_name: taskcafe
    depends_on:
      - postgres
    environment:
      - TASKCAFE_DATABASE_HOST=postgres
      - TASKCAFE_DATABASE_PORT=5432
      - TASKCAFE_DATABASE_USER=taskcafe
      - TASKCAFE_DATABASE_PASSWORD=taskcafe_secret
      - TASKCAFE_DATABASE_NAME=taskcafe
      - TASKCAFE_MIGRATE=true
      - TASKCAFE_AUTOMIGRATE=true
    ports:
      - "3333:3333"
    restart: unless-stopped

volumes:
  postgres-data: