services:
  model-service:
    build:
      context: ./model
    volumes:
      - model-data:/root/.cache
    working_dir: /app
    environment:
      - MODEL_NAME=runwayml/stable-diffusion-v1-5
    ports:
      - "8080:8000"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - model-service
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  model-data: