services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # MinIO API port
      - "9001:9001"    # MinIO console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped

volumes:
  minio-data:
